### PR TITLE
Changed file permission of lib/robots.rb, addressing issue #6.

### PR DESCRIPTION
**Pull request by Romulus10**
Changed the file permissions for `lib/robots.rb` from 644 to 755. This might not be ideal, but for now it patches issue #6.

### CODE REVIEW

**Comment by busterb** [comment]
I'm not sure if that will fix it. The issue is that the file isn't readable by all when the gem is installed, it doesn't need to be executable: https://github.com/rapid7/metasploit-omnibus/blob/master/config/software/metasploit-framework.rb#L73

I think this might be due to an overly-restrictive umask being set when the gem was last built (or maybe it was a buggy version of the gem command).

**Comment by Romulus10** [comment]
I see what you're saying. The read permissions are present now in the repository version, but now that I'm looking again it might not carry over when installed via gem.

**Comment by Romulus10** [comment]
Sorry, had a moment there - that's exactly what it was before. Well I thought I had an idea...

**Comment by busterb** [comment]
This whole gem is just one file though, and hasn't been updated in 7 years. I imagine we could probably just embed a copy and not miss out on much.

**Comment by Romulus10** [comment]
Agreed. It might be relatively painless depending on how many places we need to change where we're looking for robots.rb

**Comment by busterb** [comment]
https://github.com/rapid7/metasploit-framework/pull/8902

**Pull request closed without merging**
